apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-rag
  namespace: placebo
spec:
  rules:
    - host: test8.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enterprise-rag
                port:
                  number: 80
