apiVersion: v1
kind: Service
metadata:
  name: enterprise-rag
  namespace: placebo
  labels:
    app: enterprise-rag
spec:
  type: ClusterIP
  selector:
    app: enterprise-rag
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
